release: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

registration:
  -
    id: 1
    text: How often do you watch or listen to any kind of video or podcast online? (Never, once a year, once a month, every week, everyday?)
    response_type: text
  -
    id: 2
    text: Prior to this course, have you ever engaged in live online discussion around an event (radio show, tv program, sports event or webinar)? (Never, once a year, once a month, every week, everyday?)
    response_type: text
  - 
    id: 3
    text: How many online courses have you taken?
    response_type: scale
  -
    id: 4
    text: What do you think about online courses? Do you prefer them over traditional lectures?
    response_type: boolean
  - 
    id: 5
    text: When learning, do you prefer a lecture setting where you get delivered information by an expert or do you prefer it to be more discussion-based ?
    response_type: text
during:
  -
    id: 6
    text: How long did you take to listen to this class?
    response_type: scale
  - 
    id: 8
    text: When learning, do you prefer a lecture setting where you get delivered information by an expert
    response_type: scale
post:
  -
    id: 7
    text: How long did you take to listen to this class?
    response_type: scale
