version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker: 
      - image: node:7.4.0
    working_directory: ~/connectedacademy
    steps:
      - checkout
      - run: npm install
      - run: npm run generate
      - add_ssh_keys
      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "info@connectedacademy.io"
      - run: git checkout -b staging
      - run: git add links.jsonp *.json
      - run: git commit -am"[skip CI] AUTOBUILD"
      - run: git checkout -b gh-pages
      - run: git rebase -Xtheirs staging
      - run: git push -u -f origin gh-pages