name: "Test Class 1"
hashtag: "#test/class1"
starts: "2017-09-01T22:47:31-07:00"
ends: "2017-09-20T22:47:31-07:00"
accounts: 
  - tombartindale
langs:
  - en
  - ar
classes:
  -
    dir: /class1
    content:
      -
        content_type: "submission"
        url: intro.md
      -
        content_type: pre
        url: extra-pre-reading.md
      -
        content_type: "class"
        url: class.md
        schedule:
          -
            release_at: "2017-04-05T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
          -
            release_at: "2017-04-05T11:57:37Z"
            hub_id: "ncl"
          -
            release_at: "2017-04-05T22:57:37-07:00"
            hub_id: "irvine"
      -
        content_type: "postclass"
        url: postclass.md
      -
        content_type: "webinar"
        url: webinar.md
        schedule:
          -
            release_at: "2017-04-05T22:57:37-07:00"
      -
        content_type: "postwebinar"
        url: "deepdive.md"
      -
        content_type: "postwebinar"
        url: post1.md
      -
        content_type: "postwebinar"
        url: post2.md