hashtag: "#wpca17"
starts: "2017-09-01T22:47:31-07:00"
ends: "2017-09-20T22:47:31-07:00"
accounts: 
  - tombartindale
langs:
  - en
about: about.md
info: info.md
classes:
  -
    dir: class1
    slug: evidence
    content:
      -
        url: intro.md
        slug: intro
      -
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-05T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
          -
            release_at: "2017-04-05T11:57:37Z"
            hub_id: "ncl"
          -
            release_at: "2017-04-05T22:57:37-07:00"
            hub_id: "irvine"
      -
        content_type: question
      -
        url: extended.md
        slug: extended
      -
        url: deepdive.md
        slug: deepdive
      -
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-05T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class2
    slug: interpretation
    content:
      -
        url: intro.md
        slug: intro
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-05T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
          -
            release_at: "2017-04-05T11:57:37Z"
            hub_id: "ncl"
          -
            release_at: "2017-04-05T22:57:37-07:00"
            hub_id: "irvine"
      -
        content_type: question
      -
        url: postclass.md
        slug: postclass
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-05T22:57:37-07:00"
      -
        content_type: question
      -
        url: "deepdive.md"
        slug: deepdive
      -
        content_type: question
      -
        url: post1.md
        slug: post1
      -
        url: post2.md
        slug: post2
  -
    dir: class3
    slug: fiction
    content:
  -
    dir: class4
    slug: fact
    content:
  -
    dir: class5
    slug: narrative
    content:
  -
    dir: class6
    slug: impact
    content:
  -
    dir: class7
    slug: summary
    content: